CREATE DATABASE PROJETOS_MANUTENCAO;

CREATE TABLE PROJETOS (
    INDE_PROJ VARCHAR(50),
    END_PROJ VARCHAR(50),
    TEL_PROJ DECIMAL(11),
    TEL2_PROJ DECIMAL(11),
    STATUS_PROJ CHAR(3)
);

CREATE TABLE DISP_ELETRONICO(
	ID_DIS VARCHAR(20),
    TIPO_DISP CHAR (10),
    MARCA CHAR (10)
);

CREATE TABLE MANUTENCAO(
	PECAS VARCHAR(20)
);

INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ)
VALUES ("Evandro_Miguel", "Santa_Luzia", 32984100646);

SELECT * FROM 'projetos';